server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:

  application:
    name: infrastructure

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prices;DB_CLOSE_DELAY=-1
    username: sa
    password:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true