server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: application

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:prices
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true